# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('postee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postee', to='belt_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='fav',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote', to='belt_app.Quote'),
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='belt_app.User'),
        ),
    ]
